// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_Szkola.Data;

namespace Projekt_Szkola.Migrations
{
    [DbContext(typeof(Projekt_SzkolaContext))]
    partial class Projekt_SzkolaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projekt_Szkola.Models.Klasa", b =>
                {
                    b.Property<string>("KlasaID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NauczycielID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sala")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlasaID");

                    b.HasIndex("NauczycielID")
                        .IsUnique()
                        .HasFilter("[NauczycielID] IS NOT NULL");

                    b.ToTable("Klasa");
                });

            modelBuilder.Entity("Projekt_Szkola.Models.Nauczyciel", b =>
                {
                    b.Property<string>("NauczycielID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SumaGodzinTygodniowo")
                        .HasColumnType("int");

                    b.HasKey("NauczycielID");

                    b.ToTable("Nauczyciel");
                });

            modelBuilder.Entity("Projekt_Szkola.Models.Przedmiot", b =>
                {
                    b.Property<string>("PrzedmiotID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DlaKlasy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiczbaGodzinTygodniowo")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrzedmiotID");

                    b.ToTable("Przedmiot");
                });

            modelBuilder.Entity("Projekt_Szkola.Models.Uprawnienie", b =>
                {
                    b.Property<int>("UprawnienieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NauczycielID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UprawnienieNazwa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UprawnienieID");

                    b.HasIndex("NauczycielID");

                    b.ToTable("Uprawnienie");
                });

            modelBuilder.Entity("Projekt_Szkola.Models.Zajecia", b =>
                {
                    b.Property<int>("ZajeciaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("KlasaID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NauczycielID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrzedmiotID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("liczbaGodzinDzien")
                        .HasColumnType("int");

                    b.HasKey("ZajeciaID");

                    b.HasIndex("KlasaID");

                    b.HasIndex("NauczycielID");

                    b.HasIndex("PrzedmiotID");

                    b.ToTable("Zajecia");
                });

            modelBuilder.Entity("Projekt_Szkola.Models.Klasa", b =>
                {
                    b.HasOne("Projekt_Szkola.Models.Nauczyciel", "Nauczyciel")
                        .WithOne("Klasa")
                        .HasForeignKey("Projekt_Szkola.Models.Klasa", "NauczycielID");
                });

            modelBuilder.Entity("Projekt_Szkola.Models.Uprawnienie", b =>
                {
                    b.HasOne("Projekt_Szkola.Models.Nauczyciel", "Nauczyciel")
                        .WithMany("Uprawnienies")
                        .HasForeignKey("NauczycielID");
                });

            modelBuilder.Entity("Projekt_Szkola.Models.Zajecia", b =>
                {
                    b.HasOne("Projekt_Szkola.Models.Klasa", "Klasa")
                        .WithMany("Zajecias")
                        .HasForeignKey("KlasaID");

                    b.HasOne("Projekt_Szkola.Models.Nauczyciel", "Nauczyciel")
                        .WithMany("Zajecias")
                        .HasForeignKey("NauczycielID");

                    b.HasOne("Projekt_Szkola.Models.Przedmiot", "Przedmiot")
                        .WithMany("Zajecias")
                        .HasForeignKey("PrzedmiotID");
                });
#pragma warning restore 612, 618
        }
    }
}
